### ISSUE TITLE
Replace Existing Theme S&C Automatically

### ISSUE THREAD

**Issue by daverogers** [woothemes/subscribe-and-connect#31]
Using a WC theme that had previous S&C functionality, which I disabled when I installed this plugin (upon reading "...we would recommend that you use this plugin instead as newer themes will be relying on it for this functionality. Just disable the feature in the theme and install the plugin."). Unfortunately, this plugin does not attach to the header and has no such option in the settings' Display tab, so I assume I have to code that in? Ridiculous. There should just be an automatic override, not removing S&C from the header *entirely*

**Comment by jameskoster** [comment]
If you prefer how the theme handles this functionality then just use that :-)

This is only really going to become an issue if you switch to a theme that doesn't bundle the functionality and relies on the plugin.

**Comment by daverogers** [comment]
So, then I guess update your docs to instead say "if S&C is bundled with your theme, just use that (outdated) code, because Woothemes has become unwieldy and somehow cannot make two different parts they author to work together" :/
