### ISSUE TITLE
https for feedburner

### ISSUE THREAD

**Issue by mackaaij** [woothemes/subscribe-and-connect#32]
Chrome shows the mixed content warning in case of Subscribe & Connect with Feedburner.

You could fix this by removing "http:" from this line in "subscribe-and-connect-template.php":
$form_action 	= '//feedburner.google.com/fb/a/mailverify';

But you might also want to look into this for other mail forms.

**Comment by mackaaij** [comment]
I think the same applies to aweber:

http://www.aweber.com/scripts/addlead.pl -> //www.aweber.com/scripts/addlead.pl

**Comment by jeffikus** [comment]
@mackaaij wanna submit a pull request for this?

**Comment by mackaaij** [comment]
Sure, I've never done this before but just tried. Let me know how I did :)

**Comment by jeffikus** [comment]
Great thanks! I'll take a look!

**Comment by jeffikus** [comment]
Merged, thanks!
