### ISSUE TITLE
Undefined variable: hidden_fields for mailchimp

### ISSUE THREAD

**Issue by tarranjones** [woothemes/subscribe-and-connect#38]
I am getting the following error.  `Notice: Undefined variable: hidden_fields in C:\...wp-content\plugins\subscribe-and-connect\subscribe-and-connect-template.php on line 236`

adding `$hidden_fields 	= array();` should fix it. 

		case 'mailchimp':
			$form_action = $settings['connect']['newsletter_mail_chimp_list_subscription_url'];
			$text_fields = apply_filters( 'subscribe-and-connect-mailchimp-text-fields', array(
								'EMAIL' => __( 'Your Email Address', 'subscribe-and-connect' )
								) );
            $hidden_fields = array();

		break;

**Comment by dtjones** [comment]
just noticed its missing from `case 'madmimi':` as well.

**Comment by lsterling03** [comment]
I'm getting the same error today after adding Mailchimp.
